Fix: Alias References Action
FidelityInternational/djangocms-references pull request #33
Opened 2022-04-07 12:05 UTC by adam-murray

2022-04-07 12:27 UTC, Aiky30 requested changes
Looks good, just missing a changelog entry

2022-04-08 12:58 UTC, Aiky30 requested changes
All good but the changelog entry is off.

2022-04-08 12:58 UTC, Aiky30 commented on CHANGELOG.rst
> +* Fix: Added Alias list_action monkeypatch for references
Not a release PR.

2022-04-11 08:03 UTC, Bernardvdv approved these changes

2022-04-11 11:31 UTC, Aiky30 approved these changes

2022-04-11 11:31 UTC, merged